# Generated by Django 4.1 on 2022-09-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contactdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=20)),
                ("sname", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=30)),
                ("mobile", models.IntegerField(20)),
                ("gender", models.CharField(max_length=20)),
            ],
        ),
    ]
