# Generated by Django 4.1 on 2022-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdata",
            name="password",
            field=models.CharField(default=30, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactdata", name="mobile", field=models.IntegerField(),
        ),
    ]
