# Generated by Django 4.1 on 2022-09-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0002_contactdata_password_alter_contactdata_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdata", name="mobile", field=models.BigIntegerField(),
        ),
    ]
