# Generated by Django 4.1 on 2022-09-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0003_alter_contactdata_mobile"),
    ]

    operations = [
        migrations.RemoveField(model_name="contactdata", name="gender",),
    ]
