# Generated by Django 4.1 on 2022-09-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0004_remove_contactdata_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("mobile", models.BigIntegerField()),
            ],
        ),
    ]
