# Generated by Django 4.1 on 2022-09-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0005_contactform"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactform", old_name="email", new_name="emailid",
        ),
        migrations.RenameField(
            model_name="contactform", old_name="mobile", new_name="mobileno",
        ),
    ]
