# Generated by Django 4.1 on 2022-09-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0006_rename_email_contactform_emailid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactform", old_name="name", new_name="username",
        ),
    ]
