# Generated by Django 4.1 on 2022-09-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0007_rename_name_contactform_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdata",
            name="username",
            field=models.CharField(default=30, max_length=30),
            preserve_default=False,
        ),
    ]
