# Generated by Django 4.1 on 2022-09-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0008_contactdata_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdata",
            name="mobile",
            field=models.CharField(max_length=12),
        ),
    ]
