# Generated by Django 4.1 on 2022-09-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0010_alter_contactdata_email_alter_contactdata_fname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdata",
            name="mobile",
            field=models.CharField(max_length=120),
        ),
    ]
