# Generated by Django 4.1 on 2022-09-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0011_alter_contactdata_mobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactform", old_name="username", new_name="name",
        ),
    ]
